# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'interests',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.Interest')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
